### ISSUE TITLE
mvn test fails

### ISSUE THREAD

**Issue by dunkeki** [igor-baiborodine/campsite-booking#1]
Cloned the repo (on 10/6/2020) and, without modification, ran mvn test which failed.  Find below report.  I apologize in advance if my choice of JVM is the root of the problem...

By the way, package does build (mvn -DskipTests package) successfully and run correctly per the README - thanks!

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.515 s <<< FAILURE! - in com.kiroule.campsitebooking.service.BookingServiceImplTest
[ERROR] com.kiroule.campsitebooking.service.BookingServiceImplTest  Time elapsed: 0.515 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: interface com.kiroule.campsitebooking.repository.BookingRepository.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Java               : 11
JVM vendor name    : AdoptOpenJDK
JVM vendor version : 11.0.8+10
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.8+10
JVM info           : mixed mode
OS name            : Linux
OS version         : 5.4.0-48-generic

Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
Caused by: java.lang.IllegalStateException: Could not find sun.misc.Unsafe
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String, [B, int, int, java.lang.ClassLoader, java.security.ProtectionDomain)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BookingServiceImplTest.com.kiroule.campsitebooking.service.BookingServiceImplTest » Mockito
[INFO] 
[ERROR] Tests run: 9, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.103 s
[INFO] Finished at: 2020-10-07T15:48:22Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project campsite-booking: There are test failures.
[ERROR] 
[ERROR] Please refer to /opt/campsite-booking/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by igor-baiborodine** [comment]
This issue has been fixed.

**Comment by dunkeki** [comment]
Wonderful, thanks!
